# Generated by Django 4.1.6 on 2023-03-08 10:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='country',
            fields=[
                ('countryid', models.AutoField(primary_key=True, serialize=False)),
                ('countryname', models.TextField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='state',
            fields=[
                ('stateid', models.AutoField(primary_key=True, serialize=False)),
                ('statename', models.TextField(max_length=20)),
                ('countryid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stockImg.country')),
            ],
        ),
    ]
