# Generated by Django 4.1.6 on 2023-03-08 11:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stockImg', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='city',
            fields=[
                ('cityid', models.AutoField(primary_key=True, serialize=False)),
                ('cityname', models.TextField(max_length=20)),
                ('stateid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stockImg.state')),
            ],
        ),
    ]
