# Generated by Django 4.1.6 on 2023-03-08 11:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stockImg', '0002_city'),
    ]

    operations = [
        migrations.CreateModel(
            name='user',
            fields=[
                ('userid', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.TextField(max_length=30)),
                ('password', models.TextField(max_length=15)),
                ('email', models.TextField(max_length=50)),
                ('phone_number', models.TextField(max_length=15)),
                ('profile_pic', models.ImageField(upload_to='media/images')),
                ('bio', models.TextField(max_length=150)),
                ('register_date_time', models.DateTimeField(auto_now=True)),
                ('cityid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stockImg.city')),
            ],
        ),
    ]
