# Generated by Django 4.1.6 on 2023-03-12 09:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stockImg', '0004_user_dob_user_gender'),
    ]

    operations = [
        migrations.CreateModel(
            name='album',
            fields=[
                ('albumid', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.TextField(max_length=50)),
                ('status', models.TextField(max_length=100)),
                ('description', models.TextField(max_length=300)),
                ('thumbnail', models.TextField(max_length=200)),
                ('userid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stockImg.user')),
            ],
        ),
        migrations.CreateModel(
            name='catagory',
            fields=[
                ('catagoryid', models.AutoField(primary_key=True, serialize=False)),
                ('catagoryname', models.TextField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='img',
            fields=[
                ('imageid', models.AutoField(primary_key=True, serialize=False)),
                ('url', models.TextField(max_length=300)),
                ('is_approved', models.BooleanField()),
                ('status', models.TextField(max_length=300)),
                ('description', models.TextField(max_length=200)),
                ('price', models.IntegerField()),
                ('userid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stockImg.user')),
            ],
        ),
        migrations.CreateModel(
            name='tags',
            fields=[
                ('tagid', models.AutoField(primary_key=True, serialize=False)),
                ('tag', models.TextField(max_length=50)),
                ('catagoryid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stockImg.catagory')),
            ],
        ),
        migrations.CreateModel(
            name='save',
            fields=[
                ('saveid', models.AutoField(primary_key=True, serialize=False)),
                ('imageid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stockImg.img')),
                ('userid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stockImg.user')),
            ],
        ),
        migrations.CreateModel(
            name='like',
            fields=[
                ('likeid', models.AutoField(primary_key=True, serialize=False)),
                ('imageid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stockImg.img')),
                ('userid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stockImg.user')),
            ],
        ),
        migrations.CreateModel(
            name='comment',
            fields=[
                ('commentid', models.AutoField(primary_key=True, serialize=False)),
                ('comment', models.TextField(max_length=100)),
                ('date_time', models.DateTimeField(auto_now=True)),
                ('imageid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stockImg.img')),
                ('userid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stockImg.user')),
            ],
        ),
        migrations.CreateModel(
            name='albumimage',
            fields=[
                ('albumimageid', models.AutoField(primary_key=True, serialize=False)),
                ('albumid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stockImg.album')),
                ('imageid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stockImg.img')),
            ],
        ),
    ]
