# Generated by Django 4.1.6 on 2023-03-12 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stockImg', '0006_alter_img_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='status',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='album',
            name='thumbnail',
            field=models.ImageField(default='default.jpg', upload_to='media/images'),
        ),
        migrations.AlterField(
            model_name='img',
            name='is_approved',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='img',
            name='price',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='img',
            name='status',
            field=models.IntegerField(default=0),
        ),
    ]
