# Generated by Django 4.1.6 on 2023-03-20 13:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stockImg', '0007_alter_album_status_alter_album_thumbnail_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='city',
            new_name='ucity',
        ),
    ]
