# Generated by Django 4.1.6 on 2023-03-20 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stockImg', '0008_rename_city_ucity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='profile_pic',
            field=models.ImageField(default='default.jpg', upload_to='media/images'),
        ),
    ]
