# Generated by Django 4.1.6 on 2023-03-21 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stockImg', '0009_alter_user_profile_pic'),
    ]

    operations = [
        migrations.AddField(
            model_name='img',
            name='title',
            field=models.TextField(default='--Not Defined--', max_length=100),
        ),
    ]
