# Generated by Django 4.1.6 on 2023-03-21 13:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stockImg', '0010_img_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='img',
            name='catagoryid',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='stockImg.catagory'),
        ),
    ]
