# Generated by Django 4.1.6 on 2023-03-21 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stockImg', '0011_img_catagoryid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='img',
            name='description',
            field=models.TextField(max_length=1000),
        ),
    ]
