# Generated by Django 4.1.6 on 2023-03-25 06:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stockImg', '0013_remove_albumimage_imageid_albumimage_desc_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='albumimage',
            old_name='desc',
            new_name='description',
        ),
    ]
