# Generated by Django 4.1.6 on 2023-03-27 12:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stockImg', '0014_rename_desc_albumimage_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='albumimage',
            name='imageurl',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stockImg.img'),
        ),
    ]
