# Generated by Django 4.1.6 on 2023-03-29 12:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stockImg', '0015_alter_albumimage_imageurl'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='albumimage',
            name='description',
        ),
    ]
